FROM       jacobmbr/ubuntu-jecci:v0.1.0

RUN rm /etc/apt/apt.conf.d/docker-clean && apt-get update

# Install Jecci dependencies
RUN apt-get install -y openssh-server \
    curl faketime iproute2 iptables iputils-ping libzip4 \
    logrotate man man-db net-tools ntpdate psmisc python rsyslog \
    sudo unzip vim wget apt-transport-https \
    && apt-get remove -y --purge --auto-remove systemd
