{
 "title": "Dgraph",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Go Threads",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_threads{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Go Routines",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dgraph_memory_inuse_bytes+dgraph_memory_idle_bytes{instance=~'$Instance'}"
    },
    {
     "expr": "dgraph_memory_proc_bytes{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Read rate (1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(dgraph_read_bytes_total{instance=~'$Instance'}[1m])",
     "legendFormat": "Bytes Read"
    },
    {
     "expr": "rate(dgraph_posting_reads_total{instance=~'$Instance'}[1m])",
     "legendFormat": "Postings Read"
    }
   ]
  },
  {
   "title": "Memory Heap Idle",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dgraph_memory_idle_bytes{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Writes Rate(30s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(dgraph_written_bytes_total{instance=~'$Instance'}[30s])",
     "legendFormat": "Bytes Written"
    },
    {
     "expr": "rate(dgraph_posting_writes_total{instance=~'$Instance'}[30s])",
     "legendFormat": "Postings Written"
    }
   ]
  },
  {
   "title": "GC second sum rate(30s)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(go_gc_duration_seconds_sum{instance=~'$Instance'}[30s])"
    }
   ]
  },
  {
   "title": "Pending Proposals",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_pending_proposals_total{instance=~'$Instance'}"
    },
    {}
   ]
  },
  {
   "title": "Predicate Stats(Number of mutations)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(dgraph_predicate_stats)", "legendFormat": "All" },
    {
     "expr": "sum(dgraph_predicate_stats{instance=~'$Instance'})",
     "legendFormat": "current"
    },
    { "legendFormat": "machine2" },
    { "legendFormat": "machine4" }
   ]
  },
  {
   "title": "Mutations - All Servers (1m)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(dgraph_predicate_stats[1m]))",
     "legendFormat": "All"
    },
    {
     "expr": "sum(rate(dgraph_predicate_stats{instance=~'$Instance'}[1m]))",
     "legendFormat": "current"
    }
   ]
  },
  {
   "title": "MaxPlLength",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dgraph_max_list_bytes{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Server Health",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_alpha_health_status{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "LRU Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dgraph_lru_size_bytes{instance=~'$Instance'}",
     "legendFormat": "cacheSize"
    },
    {
     "expr": "dgraph_lru_keys_total{instance=~'$Instance'}",
     "legendFormat": "cacheLen"
    },
    {}
   ]
  },
  {
   "title": "Cache Hit,Miss,Race",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_lru_hits_total{instance=~'$Instance'}",
     "legendFormat": "cacheHit"
    },
    {
     "expr": "dgraph_lru_miss_total{instance=~'$Instance'}",
     "legendFormat": "cacheMiss"
    },
    {
     "expr": "dgraph_lru_race_total{instance=~'$Instance'}",
     "legendFormat": "cacheRace"
    }
   ]
  },
  {
   "title": "rate Evicted Pls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(dgraph_lru_evicted_total{instance=~'$Instance'}[30s])"
    },
    {}
   ]
  },
  {
   "title": "process_cpu_seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Active mutations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_active_mutations_total{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Pending Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_pending_queries_total{instance=~'$Instance'}"
    }
   ]
  },
  {
   "title": "Mutations(per predicate)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dgraph_predicate_stats{instance=~'$Instance'}"
    }
   ]
  }
 ]
}